# -*- coding: utf-8 -*-

import os

# =========================
# Environment Settings
# =========================

os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["HF_ENDPOINT"] = os.getenv("HF_ENDPOINT", "https://hf-mirror.com")

# Enable online access by default.
# Remove offline flags if they exist in the environment.
os.environ.pop("HF_HUB_OFFLINE", None)
os.environ.pop("TRANSFORMERS_OFFLINE", None)

# Disable unused deep learning backends.
os.environ["TRANSFORMERS_NO_TF"] = "1"
os.environ["TRANSFORMERS_NO_FLAX"] = "1"


import gc
from pathlib import Path

import numpy as np
import torch
from datasets import load_dataset
from peft import LoraConfig, TaskType, get_peft_model
from sklearn.metrics import f1_score, precision_score, recall_score
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)


# =========================
# Configuration
# =========================

MODEL_NAME = "bert-base-uncased"
EXPERIMENT_MODE = "P4"

# Pair ID controls which segment pair is used.
# Example:
#   PAIR_ID=00-01 python train_bert.py
PAIR_ID = os.environ.get("PAIR_ID", "00-01")
left_id, right_id = PAIR_ID.split("-")
PAIR_ID = f"{int(left_id):02d}-{int(right_id):02d}"

# Directory generated by the P4 preprocessing script.
DATA_DIR = Path("./out_bert_p4_pairs_ta")

TRAIN_FILE = str(DATA_DIR / f"train_{PAIR_ID}.jsonl")
VAL_FILE = str(DATA_DIR / f"val_{PAIR_ID}.jsonl")

OUT_DIR = Path(f"./outputs/bert/{EXPERIMENT_MODE.lower()}_{PAIR_ID}")
OUT_DIR.mkdir(parents=True, exist_ok=True)

MAX_LEN = 512
SEED = 42
LR = 5e-4
EPOCHS = 10
TRAIN_BS = 8
EVAL_BS = 16
GRAD_ACCUM = 2
NUM_LABELS = 16

# Fair truncation allocates half of the token budget to each segment.
FAIR_SPLIT = True

# Input mode:
# - "pair": use chunk_i and chunk_j as two separated text fields.
# - "text": use the concatenated text field generated by preprocessing.
INPUT_MODE = os.environ.get("INPUT_MODE", "pair")


# =========================
# Metrics
# =========================

def sigmoid_np(x: np.ndarray) -> np.ndarray:
    """Apply the sigmoid function to a NumPy array."""
    return 1 / (1 + np.exp(-x))


def compute_metrics(eval_pred):
    """
    Compute micro-averaged precision, recall, and F1 for multi-label classification.
    """
    logits, labels = eval_pred

    y_true = (labels > 0.5).astype(int)
    probs = sigmoid_np(logits)
    y_pred = (probs >= 0.5).astype(int)

    micro_f1 = f1_score(y_true, y_pred, average="micro", zero_division=0)
    micro_p = precision_score(y_true, y_pred, average="micro", zero_division=0)
    micro_r = recall_score(y_true, y_pred, average="micro", zero_division=0)

    return {
        "micro_f1": micro_f1,
        "micro_p": micro_p,
        "micro_r": micro_r,
    }


# =========================
# Tokenization
# =========================

def tokenize_pair_fair(examples, tokenizer):
    """
    Tokenize two text segments using fair truncation.

    Required fields:
        chunk_i
        chunk_j

    The maximum sequence length is divided approximately equally between
    the two segments.
    """
    chunk_i_list = examples["chunk_i"]
    chunk_j_list = examples["chunk_j"]

    content_max = MAX_LEN - 3
    len_i = content_max // 2
    len_j = content_max - len_i

    cls_id = tokenizer.cls_token_id
    sep_id = tokenizer.sep_token_id

    input_ids_list = []
    attention_mask_list = []
    token_type_ids_list = []

    for chunk_i, chunk_j in zip(chunk_i_list, chunk_j_list):
        chunk_i = "" if chunk_i is None else str(chunk_i)
        chunk_j = "" if chunk_j is None else str(chunk_j)

        if FAIR_SPLIT:
            encoded_i = tokenizer(
                chunk_i,
                truncation=True,
                max_length=len_i,
                padding=False,
                add_special_tokens=False,
            )
            encoded_j = tokenizer(
                chunk_j,
                truncation=True,
                max_length=len_j,
                padding=False,
                add_special_tokens=False,
            )

            input_ids = (
                [cls_id]
                + encoded_i["input_ids"]
                + [sep_id]
                + encoded_j["input_ids"]
                + [sep_id]
            )

            attention_mask = [1] * len(input_ids)
            token_type_ids = (
                [0] * (1 + len(encoded_i["input_ids"]) + 1)
                + [1] * (len(encoded_j["input_ids"]) + 1)
            )

            if len(input_ids) > MAX_LEN:
                input_ids = input_ids[:MAX_LEN]
                attention_mask = attention_mask[:MAX_LEN]
                token_type_ids = token_type_ids[:MAX_LEN]

            input_ids_list.append(input_ids)
            attention_mask_list.append(attention_mask)
            token_type_ids_list.append(token_type_ids)

        else:
            encoded = tokenizer(
                chunk_i,
                chunk_j,
                truncation=True,
                max_length=MAX_LEN,
                padding=False,
            )

            input_ids_list.append(encoded["input_ids"])
            attention_mask_list.append(encoded["attention_mask"])
            token_type_ids_list.append(
                encoded.get("token_type_ids", [0] * len(encoded["input_ids"]))
            )

    return {
        "input_ids": input_ids_list,
        "attention_mask": attention_mask_list,
        "token_type_ids": token_type_ids_list,
    }


def tokenize_text(examples, tokenizer):
    """
    Tokenize the concatenated text field.

    Required field:
        text

    If the text field is missing, the function falls back to pair tokenization.
    """
    texts = examples.get("text", None)

    if texts is None:
        return tokenize_pair_fair(examples, tokenizer)

    if not isinstance(texts, list):
        texts = [texts]

    texts = [("" if text is None else str(text)).strip() for text in texts]

    return tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LEN,
        padding=False,
    )


# =========================
# Main Training Procedure
# =========================

def main() -> None:
    device = "cuda" if torch.cuda.is_available() else "cpu"

    print(
        f"Using device: {device} | "
        f"Model: {MODEL_NAME} | "
        f"Experiment: {EXPERIMENT_MODE} | "
        f"Pair ID: {PAIR_ID}"
    )

    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")

    print(f"DATA_DIR: {DATA_DIR.resolve()}")
    print(f"TRAIN_FILE: {TRAIN_FILE}")
    print(f"VAL_FILE: {VAL_FILE}")
    print(f"OUT_DIR: {OUT_DIR.resolve()}")
    print(f"INPUT_MODE: {INPUT_MODE}")
    print(f"FAIR_SPLIT: {FAIR_SPLIT} | MAX_LEN: {MAX_LEN}")

    assert Path(TRAIN_FILE).exists(), TRAIN_FILE
    assert Path(VAL_FILE).exists(), VAL_FILE

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

    base_model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=NUM_LABELS,
        problem_type="multi_label_classification",
    )

    # LoRA configuration for sequence classification.
    lora_config = LoraConfig(
        r=64,
        lora_alpha=128,
        lora_dropout=0.1,
        bias="none",
        task_type=TaskType.SEQ_CLS,
        target_modules=[
            "query",
            "key",
            "value",
            "dense",
            "intermediate.dense",
            "output.dense",
        ],
        modules_to_save=["classifier"],
    )

    model = get_peft_model(base_model, lora_config)
    model.print_trainable_parameters()
    model.config.use_cache = False

    print("Loading dataset...")
    dataset = load_dataset(
        "json",
        data_files={
            "train": TRAIN_FILE,
            "validation": VAL_FILE,
        },
    )

    # Keep only the fields needed for tokenization and training.
    if INPUT_MODE == "text":
        keep_columns = {"labels", "text", "chunk_i", "chunk_j"}
        tokenize_fn = lambda batch: tokenize_text(batch, tokenizer)
        tokenization_desc = "Tokenizing P4 text input"
    else:
        keep_columns = {"labels", "chunk_i", "chunk_j"}
        tokenize_fn = lambda batch: tokenize_pair_fair(batch, tokenizer)
        tokenization_desc = "Tokenizing P4 pair input"

    remove_columns = [
        column for column in dataset["train"].column_names
        if column not in keep_columns
    ]

    dataset = dataset.map(
        tokenize_fn,
        batched=True,
        remove_columns=remove_columns,
        desc=tokenization_desc,
    )

    def cast_labels(batch):
        batch["labels"] = [[float(value) for value in y] for y in batch["labels"]]
        return batch

    dataset = dataset.map(
        cast_labels,
        batched=True,
        desc="Casting labels to float",
    )

    base_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    def collator(features):
        labels = [feature["labels"] for feature in features]

        for feature in features:
            feature.pop("labels", None)

        batch = base_collator(features)
        batch["labels"] = torch.tensor(labels, dtype=torch.float32)

        return batch

    training_args = TrainingArguments(
        output_dir=str(OUT_DIR),
        seed=SEED,

        fp16=False,
        bf16=False,

        # For newer Transformers versions, use eval_strategy.
        # For older versions, replace eval_strategy with evaluation_strategy.
        eval_strategy="steps",
        eval_steps=50,
        save_strategy="steps",
        save_steps=50,
        save_total_limit=2,
        logging_steps=10,

        learning_rate=LR,
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=TRAIN_BS,
        per_device_eval_batch_size=EVAL_BS,
        gradient_accumulation_steps=GRAD_ACCUM,

        warmup_ratio=0.1,
        weight_decay=0.01,
        max_grad_norm=1.0,

        report_to="none",

        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        disable_tqdm=False,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        data_collator=collator,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    )

    print("Starting BERT training...")
    trainer.train()

    adapter_path = OUT_DIR / "adapter"
    adapter_path.mkdir(parents=True, exist_ok=True)

    trainer.model.save_pretrained(str(adapter_path))
    tokenizer.save_pretrained(str(adapter_path))

    print(f"Saved adapter to: {adapter_path.resolve()}")

    del trainer, model, base_model, tokenizer, dataset
    gc.collect()


if __name__ == "__main__":
    main()