# -*- coding: utf-8 -*-

import os

os.environ["HF_ENDPOINT"] = os.getenv("HF_ENDPOINT", "https://hf-mirror.com")
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import gc
import re
from pathlib import Path
from typing import Dict, List

import numpy as np
import torch
import torch.nn as nn
from datasets import load_dataset
from peft import LoraConfig, TaskType, get_peft_model
from sklearn.metrics import f1_score, precision_score, recall_score
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
)


# =========================
# Configuration
# =========================

MODEL_NAME = "yorko/scibert_scivocab_uncased_long_4096"

# Directory containing P4 pair data generated by preprocessing.
DATA_DIR = Path("./out_pairs_p4_scilong_titleabs")

# Root directory for model outputs.
OUT_ROOT = Path("./outputs_p4_pairs")
OUT_ROOT.mkdir(parents=True, exist_ok=True)

MAX_LEN = 4096
SEED = 42
LR = 5e-5
EPOCHS = 10
TRAIN_BS = 4
EVAL_BS = 8
GRAD_ACCUM = 4
NUM_LABELS = 16

# Asymmetric Loss settings.
GAMMA_NEG = 4.2
GAMMA_POS = 1.0
CLIP = 0.05

EVAL_STEPS = 100
SAVE_STEPS = 100
LOGGING_STEPS = 50


# =========================
# Pair Selection
# =========================

# Pair running options:
# 1. Run a single pair:
#      PAIR_ID=00-01 python train_scibertlong.py
# 2. Run a range:
#      START_PAIR=00-01 END_PAIR=03-04 python train_scibertlong.py
# 3. Run all detected pairs if no environment variable is set.
PAIR_ID = os.environ.get("PAIR_ID", "").strip()
START_PAIR = os.environ.get("START_PAIR", "").strip()
END_PAIR = os.environ.get("END_PAIR", "").strip()


# =========================
# Truncation Strategy
# =========================

# TRUNC_MODE:
# - "budget": allocate separate token budgets to title+abstract, chunk_i, and chunk_j.
# - "longest": use standard longest-first truncation.
TRUNC_MODE = os.environ.get("TRUNC_MODE", "budget").strip().lower()

# Optional manual token budgets.
# If set to 0, default budgets are used.
MAX_TA = int(os.environ.get("MAX_TA", "0"))
MAX_I = int(os.environ.get("MAX_I", "0"))
MAX_J = int(os.environ.get("MAX_J", "0"))


# =========================
# Metrics
# =========================

def sigmoid_np(x: np.ndarray) -> np.ndarray:
    """Apply the sigmoid function to a NumPy array."""
    return 1.0 / (1.0 + np.exp(-x))


def compute_metrics(eval_pred) -> Dict[str, float]:
    """
    Compute micro-averaged precision, recall, and F1 for multi-label classification.
    """
    logits, labels = eval_pred

    y_true = (labels > 0.5).astype(int)
    probs = sigmoid_np(logits)
    y_pred = (probs >= 0.5).astype(int)

    return {
        "micro_f1": float(f1_score(y_true, y_pred, average="micro", zero_division=0)),
        "micro_p": float(precision_score(y_true, y_pred, average="micro", zero_division=0)),
        "micro_r": float(recall_score(y_true, y_pred, average="micro", zero_division=0)),
        "avg_pred_labels": float(y_pred.sum(axis=1).mean()),
    }


# =========================
# Preprocessing
# =========================

def budget_defaults(max_len: int):
    """
    Return default token budgets for P4 input.

    For max_len=4096, the default allocation is approximately:
        Title + Abstract: 1024 tokens
        Segment i: 1536 tokens
        Segment j: 1536 tokens
    """
    ta = min(1024, max_len // 4)
    remaining = max_len - ta
    i = remaining // 2
    j = remaining - i
    return ta, i, j


def preprocess(examples, tokenizer):
    """
    Tokenize P4 samples for SciBERT-long.

    Input structure:
        A = Title + Abstract + Segment i
        B = Segment j

    Global attention:
        CLS token and the A segment up to the first SEP token are assigned
        global attention.
    """
    titles = examples.get("title", [""] * len(examples["chunk_i"]))
    abstracts = examples.get("abstract", [""] * len(examples["chunk_i"]))
    chunk_is = examples.get("chunk_i", [""] * len(examples["chunk_i"]))
    chunk_js = examples.get("chunk_j", [""] * len(examples["chunk_i"]))

    if isinstance(titles, str):
        titles = [titles]
    if isinstance(abstracts, str):
        abstracts = [abstracts]
    if isinstance(chunk_is, str):
        chunk_is = [chunk_is]
    if isinstance(chunk_js, str):
        chunk_js = [chunk_js]

    input_ids_list = []
    attention_mask_list = []
    global_attention_mask_list = []

    default_ta, default_i, default_j = budget_defaults(MAX_LEN)
    ta_budget = MAX_TA if MAX_TA > 0 else default_ta
    i_budget = MAX_I if MAX_I > 0 else default_i
    j_budget = MAX_J if MAX_J > 0 else default_j

    sep_id = tokenizer.sep_token_id

    for title, abstract, chunk_i, chunk_j in zip(titles, abstracts, chunk_is, chunk_js):
        title = title or ""
        abstract = abstract or ""
        chunk_i = chunk_i or ""
        chunk_j = chunk_j or ""

        if TRUNC_MODE == "longest":
            a_text = title.strip()

            if abstract.strip():
                a_text = (
                    a_text + "\n\n" + abstract.strip()
                ).strip() if a_text else abstract.strip()

            if chunk_i.strip():
                a_text = (
                    a_text + "\n\n[Body Segment i]\n" + chunk_i.strip()
                ).strip() if a_text else chunk_i.strip()

            encoded = tokenizer(
                a_text,
                chunk_j.strip(),
                truncation=True,
                max_length=MAX_LEN,
                padding=False,
            )

        else:
            ta_text = title.strip()

            if abstract.strip():
                ta_text = (
                    ta_text + "\n\n" + abstract.strip()
                ).strip() if ta_text else abstract.strip()

            ta_ids = tokenizer(
                ta_text,
                truncation=True,
                max_length=ta_budget,
                padding=False,
            )["input_ids"]

            i_ids = tokenizer(
                chunk_i.strip(),
                truncation=True,
                max_length=i_budget,
                padding=False,
            )["input_ids"]

            j_ids = tokenizer(
                chunk_j.strip(),
                truncation=True,
                max_length=j_budget,
                padding=False,
            )["input_ids"]

            ta_text_cut = tokenizer.decode(ta_ids, skip_special_tokens=True).strip()
            i_text_cut = tokenizer.decode(i_ids, skip_special_tokens=True).strip()
            j_text_cut = tokenizer.decode(j_ids, skip_special_tokens=True).strip()

            a_text = ta_text_cut

            if i_text_cut:
                a_text = (
                    a_text + "\n\n[Body Segment i]\n" + i_text_cut
                ).strip() if a_text else i_text_cut

            encoded = tokenizer(
                a_text,
                j_text_cut,
                truncation=True,
                max_length=MAX_LEN,
                padding=False,
            )

        input_ids = encoded["input_ids"]
        attention_mask = encoded["attention_mask"]

        global_attention_mask = [0] * len(input_ids)

        if global_attention_mask:
            global_attention_mask[0] = 1

        if sep_id is not None:
            try:
                sep_index = input_ids.index(sep_id)
                for idx in range(sep_index + 1):
                    global_attention_mask[idx] = 1
            except ValueError:
                pass

        input_ids_list.append(input_ids)
        attention_mask_list.append(attention_mask)
        global_attention_mask_list.append(global_attention_mask)

    return {
        "input_ids": input_ids_list,
        "attention_mask": attention_mask_list,
        "global_attention_mask": global_attention_mask_list,
    }


def pick_lora_targets(model) -> List[str]:
    """
    Select LoRA target modules from the model.

    The function prefers attention-related modules and falls back to
    query/key/value when needed.
    """
    suffixes = set()

    for name, module in model.named_modules():
        if module.__class__.__name__ in ("Linear", "Conv1D"):
            suffixes.add(name.split(".")[-1])

    preferred = [
        "query",
        "key",
        "value",
        "query_global",
        "key_global",
        "value_global",
        "dense",
    ]

    selected = [module_name for module_name in preferred if module_name in suffixes]

    if not {"query", "key", "value"}.issubset(set(selected)):
        print("q/k/v modules were not fully detected. Falling back to query/key/value.")
        return ["query", "key", "value"]

    return selected


# =========================
# Asymmetric Loss
# =========================

class AsymmetricLoss(nn.Module):
    """
    Asymmetric Loss for multi-label classification.

    This loss down-weights easy negative labels and is useful for imbalanced
    multi-label classification tasks.
    """

    def __init__(self, gamma_neg=4.2, gamma_pos=1.0, clip=0.05, eps=1e-8):
        super().__init__()
        self.gamma_neg = gamma_neg
        self.gamma_pos = gamma_pos
        self.clip = clip
        self.eps = eps

    def forward(self, logits, targets):
        prob = torch.sigmoid(logits)

        if self.clip and self.clip > 0:
            prob = torch.clamp(prob, min=self.eps, max=1 - self.eps)
            prob_neg = torch.clamp(1 - prob + self.clip, max=1.0)
        else:
            prob_neg = 1 - prob

        prob_pos = prob

        loss_pos = targets * torch.log(prob_pos + self.eps)
        loss_neg = (1 - targets) * torch.log(prob_neg + self.eps)
        loss = loss_pos + loss_neg

        pt = prob_pos * targets + prob_neg * (1 - targets)
        gamma = self.gamma_pos * targets + self.gamma_neg * (1 - targets)
        focal_weight = torch.pow(1 - pt, gamma)

        return -(loss * focal_weight).mean()


class ASLTrainer(Trainer):
    """Trainer using Asymmetric Loss instead of the default BCE loss."""

    def __init__(self, gamma_neg=4.2, gamma_pos=1.0, clip=0.05, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.asl = AsymmetricLoss(gamma_neg=gamma_neg, gamma_pos=gamma_pos, clip=clip)

    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        loss = self.asl(outputs.logits, labels)
        return (loss, outputs) if return_outputs else loss


# =========================
# Dataset Utilities
# =========================

def load_jsonl_dataset(train_path: Path, val_path: Path):
    """Load train and validation JSONL files and cast labels to float."""
    dataset = load_dataset(
        "json",
        data_files={
            "train": str(train_path),
            "validation": str(val_path),
        },
    )

    def cast_labels(batch):
        batch["labels"] = [[float(value) for value in y] for y in batch["labels"]]
        return batch

    dataset = dataset.map(cast_labels, batched=True, desc="Casting labels")

    return dataset


def list_pairs_from_dir(data_dir: Path) -> List[str]:
    """List all available pair IDs from a data directory."""
    pattern = re.compile(r"^train_(\d{2}-\d{2})\.jsonl$")
    pairs = []

    for path in data_dir.iterdir():
        if path.is_file():
            match = pattern.match(path.name)

            if match:
                pairs.append(match.group(1))

    pairs = sorted(pairs)

    if not pairs:
        raise FileNotFoundError(f"No train_??-??.jsonl files found in {data_dir}")

    return pairs


def filter_pairs(pairs: List[str]) -> List[str]:
    """Filter pair IDs according to PAIR_ID or START_PAIR / END_PAIR settings."""
    if PAIR_ID:
        if PAIR_ID not in pairs:
            raise FileNotFoundError(f"PAIR_ID={PAIR_ID} not found. Example pairs: {pairs[:5]}")
        return [PAIR_ID]

    if START_PAIR and END_PAIR:
        if START_PAIR not in pairs or END_PAIR not in pairs:
            raise FileNotFoundError(
                f"START_PAIR or END_PAIR not found. START_PAIR={START_PAIR}, END_PAIR={END_PAIR}"
            )

        start_idx = pairs.index(START_PAIR)
        end_idx = pairs.index(END_PAIR)

        if start_idx > end_idx:
            start_idx, end_idx = end_idx, start_idx

        return pairs[start_idx:end_idx + 1]

    return pairs


def train_one(pair_name: str) -> None:
    """Train SciBERT-long on one P4 segment pair."""
    train_file = DATA_DIR / f"train_{pair_name}.jsonl"
    val_file = DATA_DIR / f"val_{pair_name}.jsonl"

    if not train_file.exists() or not val_file.exists():
        print(f"[P4_{pair_name}] Missing train or validation JSONL file. Skipping.")
        return

    raw_dataset = load_jsonl_dataset(train_file, val_file)

    if len(raw_dataset["train"]) == 0:
        print(f"[P4_{pair_name}] Empty training set. Skipping.")
        return

    out_dir = OUT_ROOT / f"P4_{pair_name}"
    out_dir.mkdir(parents=True, exist_ok=True)

    device = "cuda" if torch.cuda.is_available() else "cpu"

    print(
        f"\n=== Training P4_{pair_name} | "
        f"device={device} | "
        f"train={len(raw_dataset['train'])} | "
        f"validation={len(raw_dataset['validation'])} ==="
    )
    print(
        f"TRUNC_MODE={TRUNC_MODE} | MAX_LEN={MAX_LEN} | "
        f"MAX_TA={MAX_TA} | MAX_I={MAX_I} | MAX_J={MAX_J}"
    )

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

    base_model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=NUM_LABELS,
        problem_type="multi_label_classification",
    )

    target_modules = pick_lora_targets(base_model)

    lora_config = LoraConfig(
        r=32,
        lora_alpha=64,
        lora_dropout=0.1,
        bias="none",
        task_type=TaskType.SEQ_CLS,
        target_modules=target_modules,
        modules_to_save=["classifier"],
    )

    model = get_peft_model(base_model, lora_config)

    if hasattr(model, "gradient_checkpointing_enable"):
        model.gradient_checkpointing_enable()

    model.config.use_cache = False
    model.enable_input_require_grads()

    remove_columns = [
        column for column in raw_dataset["train"].column_names
        if column != "labels"
    ]

    dataset = raw_dataset.map(
        lambda batch: preprocess(batch, tokenizer),
        batched=True,
        remove_columns=remove_columns,
        desc=f"Tokenizing P4_{pair_name}",
    )

    base_collator = DataCollatorWithPadding(
        tokenizer=tokenizer,
        pad_to_multiple_of=8,
    )

    def collator(features):
        labels = [feature.pop("labels") for feature in features]
        batch = base_collator(features)
        batch["labels"] = torch.tensor(labels, dtype=torch.float32)
        return batch

    training_args = TrainingArguments(
        output_dir=str(out_dir),
        seed=SEED,
        report_to="none",

        bf16=torch.cuda.is_available() and torch.cuda.is_bf16_supported(),
        fp16=False,

        # For older Transformers versions, replace eval_strategy with evaluation_strategy.
        eval_strategy="steps",
        eval_steps=EVAL_STEPS,
        save_strategy="steps",
        save_steps=SAVE_STEPS,
        save_total_limit=2,
        logging_steps=LOGGING_STEPS,

        learning_rate=LR,
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=TRAIN_BS,
        per_device_eval_batch_size=EVAL_BS,
        gradient_accumulation_steps=GRAD_ACCUM,

        warmup_ratio=0.1,
        weight_decay=0.01,
        max_grad_norm=1.0,

        load_best_model_at_end=True,
        metric_for_best_model="eval_micro_f1",
        greater_is_better=True,

        disable_tqdm=False,
    )

    trainer = ASLTrainer(
        gamma_neg=GAMMA_NEG,
        gamma_pos=GAMMA_POS,
        clip=CLIP,
        model=model,
        args=training_args,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
        data_collator=collator,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )

    trainer.train()

    adapter_dir = out_dir / "adapter"
    adapter_dir.mkdir(parents=True, exist_ok=True)

    trainer.model.save_pretrained(str(adapter_dir))
    tokenizer.save_pretrained(str(adapter_dir))

    print(f"[P4_{pair_name}] Adapter saved to: {adapter_dir}")

    del trainer, model, base_model, tokenizer, dataset, raw_dataset
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def main() -> None:
    pairs = list_pairs_from_dir(DATA_DIR)
    run_pairs = filter_pairs(pairs)

    print(f"DATA_DIR: {DATA_DIR}")
    print(f"OUT_ROOT: {OUT_ROOT}")
    print(f"Found pairs: {len(pairs)}")
    print(
        "Will run pairs:",
        run_pairs[:10],
        "..." if len(run_pairs) > 10 else "",
    )

    for pair in run_pairs:
        train_one(pair)


if __name__ == "__main__":
    main()